### ISSUE TITLE
Linux compile error lasreader_las.cpp:1466:35

### ISSUE THREAD

**Issue by jwend** [LAStools/LAStools#10]
Compile error with Ubuntu 14.04 LTS g++ version 4.8.4:
lasreader_las.cpp:1466:35: error: ‘fabs’ was not declared in this scope
       if (fabs(temp - header.min_x) > header.x_scale_factor)

Cause, starting at line 39:
`#ifdef _WIN32
#include <fcntl.h>
#include <io.h>
#include <math.h>
#endif
`
Fix:
`#include <math.h>`
needs to be outside #ifdef _WIN32 block.

**Comment by rapidlasso** [comment]
Was solved by avoiding use of fabs() ...
