### ISSUE TITLE
simple question about lasreader->read_point()

### ISSUE THREAD

**Issue by bigbrotherwei** [LAStools/LAStools#101]
firstly, l use " while (lasreader->read_point())" to get all points, next time when l set a filter and want to get points again, l find the method "lasreader->read_point()" always returns null .How can l get the result with filter again ?

**Comment by rapidlasso** [comment]
This is done via a reopen() call. See how it is done [when 'extra_pass' is true in las2las](https://github.com/LAStools/LAStools/blob/master/src/las2las.cpp#L1910).
