### ISSUE TITLE
Integer overflow in LASquadtree

### ISSUE THREAD

**Issue by Jean-Romain** [LAStools/LAStools#105]
In lasquadtree.cpp there is a loop on `l = [0, 23]` doing:

https://github.com/LAStools/LAStools/blob/a371fa330599b480e33582dbd076f4ffbd213cb4/LASzip/src/lasquadtree.cpp#L1662

`level_offset` being an array of `U32` aka unsigned 32 bits integer, at `l = 16` this run into integer overflow which is undefined behavior. On my computer with my compiler `(1<<l)*(1<<l)` is equal to `0` for `l >= 16`.

**Comment by rapidlasso** [comment]
What was I thinking here? I guess I'll just shorten the loop. Seems enough at l = 15 it's more than enough tiles for LAStools use cases.
