### ISSUE TITLE
Liblas compile linked to laszip <laszip/laszipper.hpp>

### ISSUE THREAD

**Issue by marcel-bariou** [LAStools/LAStools#106]
PlaformUbuntu 20. 04 Lastools current dev version,  Liblas 1.8.1 and current dev version
Hello,  in a not so far  release ~ 2 month ago #include <laszip/laszipper.hpp> was visible in lastools it disappears why ? Thanks for any follow up

**Comment by rapidlasso** [comment]
Liblas is a project by Howard Butler and his team and completely separate from LAStools.
