### ISSUE TITLE
Ubuntu problem

### ISSUE THREAD

**Issue by UralmashFox** [LAStools/LAStools#109]
![image](https://user-images.githubusercontent.com/55876841/118967430-61e97700-b973-11eb-860b-eec381223506.png)

hi! Does your plugin suitable with ubuntu? Try to do las2dem or anything, it doesn't work due to having extra folder 'bin' in the path - however the full path to the las2dem is /home/marina/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LAStools/LAStools in my case

**Comment by rapidlasso** [comment]
We have Linux-Beta-Binaries ready for testing: Write me a personal mail to get the download link if you want to test this as plugin for QGIS.
