### ISSUE TITLE
lastile can't output binary/text files, despite documentation saying so

### ISSUE THREAD

**Issue by PeterTillema** [LAStools/LAStools#110]
Title says it all (hopefully). I can't seem to output any different format than `.las`, while I need `.txt`. Or am I missing something?

Currently I use `lastile -i XXX.laz -otxt -oparse xyz -tile_size 512`

**Comment by rapidlasso** [comment]
That could be. You might be the first one trying this. Given how inefficient ASCII text is, performance does not seem a concern here. So I suggest you first do a tiling to LAZ and then use las2txt to convert from LAZ to TXT.
