### ISSUE TITLE
functions declared but not defined better be removed

### ISSUE THREAD

**Issue by lancewoo** [LAStools/LAStools#112]
https://github.com/LAStools/LAStools/blob/f88aec970ef9d606803f4444db19d9ebf4c41aa6/LASlib/inc/lasreader.hpp#L194

void set_neighbor_file_name(const CHAR* neighbor_file_name, BOOL unique=FALSE);
Check the above function. It's not defined actually.

https://github.com/LAStools/LAStools/blob/f88aec970ef9d606803f4444db19d9ebf4c41aa6/LASlib/inc/lasreader.hpp#L238

`  void set_ignore(LASignore* ignore);` 
should also be removed or replaced with
`  inline void set_ignore(LASignore* ignore){ this->ignore = ignore; };`

**Comment by rapidlasso** [comment]
Okay.
