### ISSUE TITLE
Activating LAStools license in Linux

### ISSUE THREAD

**Issue by oh231** [LAStools/LAStools#115]
Hi. I am trying to use all the fancy LAStools features in Linux. Activating LAStools license seems pretty much straightforward in Windows but it does not seem so in Linux. The first thing that I encounter in the Linux is that lascopy is not created in the /bin/ directory after I "make". Could somebody please give me an advice how I can overcame this issue? Cheers.

**Comment by rapidlasso** [comment]
There is no Linux version of LAStools.

**Comment by smcavoy12** [comment]
@oh231 It seems to work ok with Wine on Linux
