### ISSUE TITLE
Executables aren't installed

### ISSUE THREAD

**Issue by yurivict** [LAStools/LAStools#120]
Version 2.0

**Comment by BB-Heidelberg** [comment]
Please precise! There is nothing to install. Unzip the zip. Run the tools in the .\bin directory.

**Comment by yurivict** [comment]
It builds these executables and doesn't install them:
```lasindex las2txt las2las txt2las lasdiff lasinfo laszip lasmerge lasprecision```

**Comment by BB-Heidelberg** [comment]
Perfect. If this executables are build just use them. See the *_README.txt file in the bin dir if you need further information about the tools.

**Comment by yurivict** [comment]
In order to use them they need to be installed.

**Comment by kannes** [comment]
Says who and why?

**Comment by yurivict** [comment]
>> In order to use them they need to be installed.

> Says who and why?

Binaries are built, then the project is installed, packaged, distributed.
Binaries aren't in the package. It's kind of hard to use something that doesn't exist on the system.

**Comment by kannes** [comment]
Which package are you referring to? Which/what "system"?

The package LASTools.zip from https://github.com/LAStools/LAStools/releases/tag/v2.0.0 does include the binaries.

**Comment by yurivict** [comment]
[Here](https://cgit.freebsd.org/ports/tree/misc/lastools/Makefile) executables have to be installed manually because the project doesn't install them.

**Comment by kannes** [comment]
I am sorry but you are being very difficult to help. Please write a detailed description what you are using, what you are doing and what you want the result to be. Otherwise this is a pointless waste of time and probably not a bug of LASTools at all.

**Comment by yurivict** [comment]
I maintain the FreeBSD port linked above.
The port builds the package that is missing executables.
Instructions to install executables have to be added to the port manually.
The project should install them by itself.

**Comment by esilvia** [comment]
Sounds like a cmake thing: https://cmake.org/cmake/help/book/mastering-cmake/chapter/Install.html

i.e., he's expecting the Makefile for lastools or laslib to do... something when he invokes `make install`. The only thing I see in the script linked by @yurivict is removing the "64" suffix from some of the executables.

**Comment by yurivict** [comment]
Sorry, my bad.

The executables are actually installed by the project.

Sorry about the confusion.

**Comment by kannes** [comment]
Thank you for maintaining that port and allowing others to benefit from your packaging!

**Comment by yurivict** [comment]
You are welcome!

Thank you for developing the project!

**Comment by kannes** [comment]
Oh I am just a user who sometimes tries to help triage bug reports here and there :)
