### ISSUE TITLE
Cloud optimized point cloud support

### ISSUE THREAD

**Issue by wiesehahn** [LAStools/LAStools#121]
Hi, 
As far as I know the handling of cloud optimized point cloud data ([copc.io]()) is not yet support by LAStools. 
Are there any plans for this?

**Comment by BB-Heidelberg** [comment]
As soon there is a "strong" request we will implement this. You are the first so far :)

**Comment by Jean-Romain** [comment]
What do you mean by _strong_? I'm supporting this request. COPC is interesting and can become a standard but only if the biggest players provide a support for it.

**Comment by wiesehahn** [comment]
I still think it would be a good addition, as the format is gaining more traction (e.g. COPC support in recent QGIS version).

**Comment by lgouzin** [comment]
I randomly found it, it is now in Lastools. Works much quicker than importing a LAS straight to QGIS.
https://lastools.github.io/download/lascopcindex_README.md

**Comment by wiesehahn** [comment]
thanks to @Jean-Romain
