### ISSUE TITLE
error strdup was not declared in this scope

### ISSUE THREAD

**Issue by cyborgdennett** [LAStools/LAStools#129]
Hello, I tried installing, so I unzip and go to the root file and do make.

device: Windows11, intel 10th gen i7

This is the  output:

cd LASlib && make
make[1]: Entering directory '/c/Users/caspe/Downloads/LAStools/LAStools/LASlib'
cd src && make
make[2]: Entering directory '/c/Users/caspe/Downloads/LAStools/LAStools/LASlib/src'
g++  -c -O3 -Wall -Wno-deprecated -Wno-strict-aliasing -Wno-write-strings -Wno-unused-result -DNDEBUG -DUNORDERED -DHAVE_UNORDERED_MAP -std=c++11 -I/usr/include/ -I../../LASzip/src -I../inc -I. ../../LASzip/src/laszip.cpp -o ../../LASzip/src/laszip.o
../../LASzip/src/laszip.cpp: In member function 'bool LASzip::return_error(const char*)':
../../LASzip/src/laszip.cpp:196:20: error: 'strdup' was not declared in this scope; did you mean 'strcmp'?
  196 | #define CopyString strdup
      |                    ^~~~~~
../../LASzip/src/laszip.cpp:201:18: note: in expansion of macro 'CopyString'
  201 |   error_string = CopyString(err);
      |                  ^~~~~~~~~~
make[2]: *** [Makefile:22: ../../LASzip/src/laszip.o] Error 1
make[2]: Leaving directory '/c/Users/caspe/Downloads/LAStools/LAStools/LASlib/src'
make[1]: *** [Makefile:2: all] Error 2
make[1]: Leaving directory '/c/Users/caspe/Downloads/LAStools/LAStools/LASlib'
make: *** [Makefile:2: all] Error 2

**Comment by rapidlasso** [comment]
please read the README carefully: "For Linux and MacOS the makefiles are included".
For Windows: Best use the downloadable binaries. You may also build yourself using cmake or the given project files - but you may need some knowledge about the tools.
