### ISSUE TITLE
e572las - Conversion flatten the point cloud around axis

### ISSUE THREAD

**Issue by Pourfex** [LAStools/LAStools#154]
Hello,

I have a huge point cloud (4go .e57) that I want to convert to Las.
I used e572las + laszip to do so.

Here is some visualisation in cloud compare : 

<img width="1505" alt="image" src="https://github.com/LAStools/LAStools/assets/25880714/f80df181-f5a4-4988-9658-5a5cc3764ac2">

During the e572las conversion, the point cloud is flatten around an axis and is not usable anymore.
Wondering if there any option to workaround this problem.

<img width="729" alt="image" src="https://github.com/LAStools/LAStools/assets/25880714/c87c90ef-7ee2-40a6-ae71-9960baec4fc3">
<img width="1449" alt="image" src="https://github.com/LAStools/LAStools/assets/25880714/6bab5c61-98bf-4fe3-96f5-1ce88b5cac38">

Best regards.

**Comment by rapidlasso** [comment]
Hi,
this is a support question: If you want support please post this to the [LAStools GG](https://groups.google.com/g/lastools).
Please make sure to follow the [rules about good service questions](https://rapidlasso.de/service/).
(Provide a sample, provide information about exactly what you did,...)
Thanks!
