### ISSUE TITLE
Special character error

### ISSUE THREAD

**Issue by ketourneau** [LAStools/LAStools#155]
On windows, if we try to use path like 
```lasinfo64.exe -i "C:\Users\...\testé - Copie.las"```

And we got error

```ERROR: cannot open file 'C:\Users\...\testÚ - Copie.las ERROR: cannot open file 'C:\Users\...\testÚ - Copie.las' for read```

I think something missing on https://github.com/LAStools/LAStools/pull/128 ?

**Comment by rapidlasso** [comment]
LASlook does not support non ansi chars in path or filename. Please replace "é" and it will work.

**Comment by ketourneau** [comment]
Our customer have some path like : `C:\Users\Sébastien\Downloads...` so we can't rename.

**Comment by jmckenna** [comment]
If it helps, this was a long-standing issue for users of MapServer, on Windows, and it was finally fixed in 2020.  I'll paste the issue here, as maybe the fix would be useful to LAStools devs : https://github.com/MapServer/MapServer/issues/5995
