### ISSUE TITLE
Attribute (Intensity, gpstime, PointSourceID) values all Zero after classifying ground

### ISSUE THREAD

**Issue by wiesehahn** [LAStools/LAStools#159]
When I classify ground points with `lasground` or  `lasground_new` all values of certain attributes (Intensity, gpstime, PointSourceID) are 0 in the new file, while oher attributes (except Classification obviously) remain unchanged
Any idea why this happens?

**Comment by rapidlasso** [comment]
lasground is not part of this git repo. Please post this to the [user group](https://groups.google.com/g/lastools). Please provide much more information of what you did and best assign a small data sample (so we can see the LAS format version,...)

**Comment by wiesehahn** [comment]
Ok, I wrote the question (and answer) there at [https://groups.google.com/d/msgid/lastools/75410886-9a81-4154-808c-673079317608n%40googlegroups.com](https://groups.google.com/d/msgid/lastools/75410886-9a81-4154-808c-673079317608n%40googlegroups.com?utm_medium=email&utm_source=footer).

 It was just my fault as I accidentally used the free version and didnt read the dedicated warning:
> WARNING: unlicensed. over 1.5 million points. output slightly distorted. 
tiny xyz noise. points permuted. intensity, gps_time, user_data & point_source_ID zeroed.
