### ISSUE TITLE
Packaging for LASlib?

### ISSUE THREAD

**Issue by sgiraudot** [LAStools/LAStools#18]
Hello,

LASlib is only available inside the LAStools package: will it be, at some point, available separately with a full installation mechanism?

So far the `Makefile` for LASlib only provides `make`, not `make install` and as far as I can see in the examples, the library is included/linked with hard coded `gcc` arguments/paths. It would be interesting to provide, for example, a `laslib-config.cmake` the same way _liblas_ does.

Are there any plans for this kind of feature?

**Comment by rapidlasso** [comment]
There is no plan for such a feature as the main reason for LASlib to exist is to be the engine for LAStools. But the honest reason why it is not likely to exist soon I have never used or learned about "make install". Feel free to add it to the Makefile and make a pull request. I will only merge it if it remains really simple (so it does not give me cross platform Linux / MacOS headaches).
