### ISSUE TITLE
LAStools/LASlib/src/lasfilter.cpp file encoding error, compilation failed in some IDEs.

### ISSUE THREAD

**Issue by kancve** [LAStools/LAStools#203]
LAStools/LASlib/src/lasfilter.cpp:

In notepad++
![lasfilter_cpp](https://github.com/user-attachments/assets/2b174ab3-a0a0-48be-8976-3cfa55eef49f)

In vscode
![lasfilter_cpp_vscode](https://github.com/user-attachments/assets/8575a9bd-8e3a-44c9-8c43-a4496a985720)

Would it be more appropriate to modify it as follows?

```cpp
// convert the first number in a input string to the out float
// if the string ends with [d/D] or [p/P] the out value will be 
// converted from [d]ecimal or [p]ercent unit
// outside of class > will be moved external soon...
BOOL strToFloatDegPcFail(const CHAR* cin, F32* out)
{
  if (sscanf(cin, "%f", out) == 1)
  {
    if ((tolower(cin[strlen(cin) - 1]) == 'd') || (tolower(cin[strlen(cin) - 1]) == 0xb0)) { *out /= 360; } // 0xb0
    if ((tolower(cin[strlen(cin) - 1]) == 'p') || (tolower(cin[strlen(cin) - 1]) == '%')) { *out /= 100; }
    return false;
  }
  return true;
}
```

**Comment by rapidlasso** [comment]
the ansi char ° (0xB0) is not displayed correct in your editors because they use UTF-8 encoding for an ansi file.
we will convert to 7bit ascii.
