### ISSUE TITLE
LAS2DEM utility produces elevation values equal to '0'

### ISSUE THREAD

**Issue by chuxohl** [LAStools/LAStools#207]
I downloaded a LAZ file from TNRIS.org which is the Texas Geographic Information Office. I used the las2dem(file) option and picked the input laz file. I took all the defaults (step 1 and keep class 2). The DEM I got back had a number of linear stripes left in it. When I queried the stripe with the Identify Features tool I got a popup that indicated the value was zero. I tried changing to a step size of 2 to no avail. Stripes were still present.

I returned to the layer properties and discovered that the default Classification choice for symbology contained only the values of 'Unclassified' and 'Ground'. Thinking the 'Unclassified' was a problem I filtered them out and reran the process. This tool results in the same exact stripes.

My instinct suggests the conversion to raster has an issue. I do not know how to handle this situation. Please advise!
![las2dem](https://github.com/user-attachments/assets/2a3a0b84-0749-4255-8fb2-d17bc561f83e)
![las2dem2](https://github.com/user-attachments/assets/c9fafe5a-a97a-4e16-986d-e5d9e17358a5)

**Comment by BB-Heidelberg** [comment]
Please attend the log output of las2dem: This is a commercial tool and only free up to ~3 million points. Consider to buy a license for larger files.
