### ISSUE TITLE
From source build fails in LasInfo

### ISSUE THREAD

**Issue by yvyork** [LAStools/LAStools#213]
**Description**: I'm encountering a compilation error when building the project on my machine using Visual Studio. The error occurs in the LasTool_lasinfo::run() method, where the compiler expects the method to return a value. However, the method ultimately calls byebye(), which invokes exit() and terminates the program, meaning no return value is necessary.

**Error Message:** `error C4716: 'LasTool_lasinfo::run': must return a value`

I use Visual Studio 2022 on Windows 11 with Microsoft (R) C/C++ Optimizing Compiler Version 19.41.34120 for x86

**Possible Solution**

- Refactor ::run() to return void since run() never reaches its end because of exit() call in byebye()
- Remove call to exit() in byebye() and return exit code instead to main() and let main() terminate the program and return exit code to user.

Let me know if you need any further information, or if there's something specific I should change in my environment to resolve the issue. (For now I made run() void)
Thanks!

**Comment by rapidlasso** [comment]
we want to centralize exit with defined exit codes & byebye was not always reached because of prior "return lasinfo_gui(...".
fix with [8fc8562](https://github.com/LAStools/LAStools/commit/8fc8562ed1376ed173b29fc3271f3500108aa620)
