### ISSUE TITLE
las2las clip_to_bounding_box no longer recognized

### ISSUE THREAD

**Issue by FevetS** [LAStools/LAStools#218]
Running las2las with clip_to_bounding_box yields ERROR: '-clip_to_bounding_box' is no longer recognized. check documentation with '-h'. But, this argument is listed in the third paragraph of the las2las readme. It should be renamed "crop_to_bounding_box" there.

**Comment by rapidlasso** [comment]
The argument "-clip_to_bounding_box" changed to "-crop_to_bounding_box" for a while, because "-clip..." wasn't passed to the argument parser at las2las (if I remember right...). So just use "-crop_to_bounding_box" instead. We will fix the readme.
