### ISSUE TITLE
Question: lasmerge license?

### ISSUE THREAD

**Issue by davidelahoz** [LAStools/LAStools#222]
I'm considering using lastools plugin for Qgis for merging a set of las files, but I'm not sure if I need to buy a license.

According to this repo and rapidlasso, that tool is open source and free to use, but Qgis plugin states that it is closed source and requires buying a license for working with point clouds with more than 3 million points

Is it just free if you use it outside of Qgis?

**Comment by rapidlasso** [comment]
lasmerge is a open source tool. There is no difference if you use a tool within or outside QGiS. QGIS just calls the tool by command line.

**Comment by rapidlasso** [comment]
It is a documentation issue: We will fix this and mark lasmerge as open source.
