### ISSUE TITLE
Missing laszip_common.h when installing on Linux

### ISSUE THREAD

**Issue by EvanZarrella** [LAStools/LAStools#223]
Currently trying to compile LAStools from source on Linux.
From what I get from the documentation, the process of compiling and installing LAStools should look like :
```
git clone https://github.com/LAStools/LAStools
cd LAStools
cmake .
cmake --build .
make
sudo make install
```

While the library is correctly installed, when trying to compile against it, it finds that `laszip_common.h` is missing meaning that those files are not copied when installing. And I tried installing LASzip then LAStools without much success.

A workaround for anyone interested is to simply copy the files where they are needed : `~/LAStools/LASzip/include/laszip$ sudo cp ./* /usr/local/include/LASlib/`

**Comment by EvanZarrella** [comment]
Ok so it's basically what #208 is doing, but now it's got an issue attached

**Comment by Ylannl** [comment]
I can confirm this issue.
