### ISSUE TITLE
strdup

### ISSUE THREAD

**Issue by afabri** [LAStools/LAStools#24]
In the file `laszip.cpp` is a `#define`:

`#if defined(_MSC_VER) &&    (_MSC_FULL_VER >= 150000000)`
`#define CopyString _strdup`
`#else`
`#define CopyString strdup`
`#endif` 

@rapidlasso What about putting that in a more central header and replacing the strdup all over the place? I could do that if you agree. It could also be called `LASstrdup`.

Doing that would avoid lots of warnings for VC++.

**Comment by rapidlasso** [comment]
Should be solved now.
