### ISSUE TITLE
las2las: branch never taken

### ISSUE THREAD

**Issue by kjk** [LAStools/LAStools#26]
In https://github.com/LAStools/LAStools/blob/master/src/las2las.cpp#L792 there is:
```
if (set_ogc_wkt) // maybe also set the OCG WKT 
{
    ....
} else if (set_ogc_wkt) // maybe only set the OCG WKT 
{
   **** this part will never execute ******
   ....
}
```

I'm not sure what the intent here was but the part in `else if (set_ogc_wkt)` branch will never execute.

If `set_ogc_wkt` is true, then one the first if () branch will execute. If it's false, then neither will execute.

**Comment by rapidlasso** [comment]
Not true. The bracketing of the code is:

if (geoprojection ...)
{
   if (set_ogc_wkt) // maybe also set the OCG WKT 
   {
       ....
   }
} else if (set_ogc_wkt) // maybe only set the OCG WKT 
{
   ....
}
