### ISSUE TITLE
About the behavior of StreamingMedian5 

### ISSUE THREAD

**Issue by Wanwannodao** [LAStools/LAStools#46]
The paper, "[LASzip: lossless compression of LiDAR data](https://www.cs.unc.edu/~isenburg/lastools/download/laszip.pdf)", says as follows:
>the median of the five immediately preceding differences of points with the same return map m

 (with the same  `current_context` and `m << 1 | gps_time_change` in v3).

However, I think SM5 behaves differently from the description.

An example of changes of SM5's `values`  is listed below.
```
0,0,0,0,0
0,0,0,0,25
0,0,0,22,25
0,0,22,22,25
-63,0,22,22,25
-63,-18,0,22,22
-63,-19,-18,0,22
-63,-19,-19,-18,0
```

According to the doc. , the sixth line should be [-63, -18, 22, 22, 25],
but actually is [-63, -18, 0, 22, 22]. 25 has been popped and 0 is still in the buffer.
This means SM5 doesn't hold the five immediately preceding differences.

I may be misunderstanding, but is this intended behavior ?

**Comment by rapidlasso** [comment]
Whatever the behaviour is now, it's the intended behaviour. This code is at the core of LASzip so it will continue to do what it does today until LAZ exists. Do you have a better formulation for the actual behaviour that we can use?
