### ISSUE TITLE
Missing raw_classification from las2txt

### ISSUE THREAD

**Issue by post2web** [LAStools/LAStools#53]
I am trying to export the value of "raw_classification" from a las file to a CSV file. There is an option "c" for "-parse" to export the classification but in my las files, there is a filed "raw_classification" that has a different value. Any suggestions on how to get to the "raw_classification" values?

**Comment by rapidlasso** [comment]
Ask the laspy guy. The LA spy guy? Or the LAS py guy?

**Comment by post2web** [comment]
I guess the LAS py guy. Will do so. Thanks

**Comment by Jean-Romain** [comment]
@post2web 

According to the documentation of `laspy` what they called the `raw_classification` is the 3 bits flags that come along with the 4 bits of the classification value it self. http://laspy.readthedocs.io/en/latest/tut_background.html

> ### Sub-Byte Fields: Point Formats 0-5
>
> There are two bytes per point record dedicated to sub-byte length fields, one called by laspy flag_byte and the other called raw_classification. These are detailed below, and are available from Laspy in the same way as full size dimensions:

See also the [las specifications](https://www.asprs.org/a/society/committees/standards/LAS_1_4_r13.pdf) page 11

They are accessible in `las2txt`via the option h - withheld flag, k - keypoint flag, g - synthetic flag.

**Comment by post2web** [comment]
Can you give me an example of how to use the h, k and g options in order to get the "raw_classification" with las2txt. Here is an example las file that has classification and "raw_classification" files in it: https://drive.google.com/open?id=1GQejKNs9RTYNUS-FLmd4z9NXZLF9wm77

**Comment by rapidlasso** [comment]
The place to get "free consultation" for LAStools is not the github account but the [LAStools user forum](http://groups.google.com/group/lastools). Please re-ask your question [there](http://groups.google.com/group/lastools). Also please include a [lasinfo report](https://rapidlasso.com/lasinfo) with your question and  - if at all possible - please provide a link to the data in [compressed LAZ](http://laszip.org) format, not in LAS format.

**Comment by post2web** [comment]
I will do so. Thank you for your guidance!
