### ISSUE TITLE
Cannot split LAS - cannot understand argument '--split-mb'

### ISSUE THREAD

**Issue by AmitMY** [LAStools/LAStools#58]
Running a simple las2las on Mac OS with `--split-mb 15` fails with: 
> cannot understand argument '--split-mb'

On Linux, I installed using `apt` and it works.
On MacOS, I just ran `make`

**Comment by rapidlasso** [comment]
The command line argument '--split-mb 15' is not a LAStools command line. Might be from libLAS.
