### ISSUE TITLE
L-GPL license question

### ISSUE THREAD

**Issue by mousebird** [LAStools/LAStools#6]
I'd like to use LAStools to interface to my [geospatial display library](http://mousebird.github.io/WhirlyGlobe/).  My library is open source, so it presents me no real problem, but I know my users won't pay attention to the license of anything I use.  I have to pay attention for them.

My question is if you have an L-GPL exemption for static linking on iOS.  The dynamic replacement requirement of that license is really impossible to meet on shipping iOS apps.

**Comment by mousebird** [comment]
Just found [this](https://groups.google.com/forum/#!topic/lastools/Bs9YBXzXXcg).  Answers my question.

**Comment by rapidlasso** [comment]
The LASzip library (not the LASlib library or any of the LAStools) have a
static linking exception for exactly that purpose.

http://github.com/LAStools/LAStools/blob/master/LASzip/LICENSE.txt

Hope this helps ...

Martin
