### ISSUE TITLE
Impossible to process files if path falsely hints at "compression"

### ISSUE THREAD

**Issue by kannes** [LAStools/LAStools#64]
https://github.com/LAStools/LAStools/blob/master/LASlib/src/fopen_compressed.cpp#L331 uses strstr to look at filenames when trying to determine if they are compressed data. This also triggers if uncompressed files are stored in a directory with e.g. ".zip" in its name.

You can test like:

```
mkdir /tmp/test.zip
touch /tmp/test.zip/foo.xyz
txt2las -i /tmp/test.zip/foo.xyz ...
```

I have no idea about C++ but I guess strstr matches anywhere in the string. The solution would be to make it match only at the end, à la "\.zip$" if it was a regular expression.

**Comment by rapidlasso** [comment]
Thanks for reporting. Fixed (I hope) with this commit: https://github.com/LAStools/LAStools/commit/96f0a569184582ab272c1e974c3f48f84bda2d67
