### ISSUE TITLE
Installation of pcs.csv

### ISSUE THREAD

**Issue by psalvaggio** [LAStools/LAStools#66]
Hi,

I'm currently packaging LASlib and LASzip up in an RPM and installing them on my system so that I can write out .laz files from my application. If I use UTM systems, this works great, as those are hard-coded into the coordinate conversion code. However, I'm trying to write the point clouds out in spherical mercator coordinates, which require a lookup to the pcs.csv file. Where should I be putting this file so that it can be found by the library? Would it be possible to make this a build-time configuration parameter? It would be awesome if I could just dump it in /usr/share/LAStools, where I'm also dumping some CMake config that I generated for the library.

Thanks,
Phil

**Comment by rapidlasso** [comment]
The pcs.csv and other files are in the .\serf\geo directory. See lines like these here where the path is formed:

https://github.com/LAStools/LAStools/blob/master/src/geoprojectionconverter.cpp#L1853
