### ISSUE TITLE
Extracting las file from rosbag pointcloud2 message

### ISSUE THREAD

**Issue by ethan20120** [LAStools/LAStools#76]
Hi,

Is there any tool or platform available which directly converts the rosbag pointcloud2 message into las file ?

Thanks

**Comment by rapidlasso** [comment]
I guess nobody who reads this page reads ROS pointclouds directly. Not a LAStools issue.

**Comment by langeroo** [comment]
For what it's worth, PDAL has pcd to las. I think that's the closest you might get.
