### ISSUE TITLE
One definition rule (ODR) violated

### ISSUE THREAD

**Issue by Jean-Romain** [LAStools/LAStools#78]
In `lasreaditemcompressed_v3.cpp` you defined `LASpoint14`. There is another definition of `LASpoint14` in `laswriteitemcompressed_v3.cpp` that is slightly different. The same in `v4.cpp`.  This violate the one definition rule of C++. See [this post](https://akrzemi1.wordpress.com/2016/11/28/the-one-definition-rule/) for more details on possible consequences.

I cannot fix it because I don't know if it is an error in the struct definition or an error in the choice of names. I think you missed in the two reader files these attributes.

```cpp
  U8 legacy_synthetic_flag : 1;
  U8 legacy_keypoint_flag  : 1;
  U8 legacy_withheld_flag  : 1;
```

If the differences were intentional, then the two definitions should not share the same name.

Best

**Comment by rapidlasso** [comment]
Nice find. Never heard of that ODR rule but certainly makes sense. Fixed in https://github.com/LAStools/LAStools/commit/73c6c0fcefb2a1b1f36cd280b6aef45cf21cd3b6
