### ISSUE TITLE
Misleading wording in -compute_density

### ISSUE THREAD

**Issue by Eskapp** [LAStools/LAStools#83]
When using lasinfo with argument `-cd`, the wording about the unit used is misleading.
Indeed, it seems that when the horizontal unit is unknown, the density is said to be in points `per square unit`. (This line in the code: https://github.com/LAStools/LAStools/blob/master/src/lasinfo.cpp#L4078)

Square unit is actually a unit that is defined as 100 square feet (as defined here: https://en.wikipedia.org/wiki/Square_(unit)).

Could you confirm that the `square unit` displayed in lasinfo does not correspond to the official square unit definition? Also, maybe a rewording could be done to avoid confusion.

**Comment by rapidlasso** [comment]
I did not know such an alternate definition for "square" existed. I simply use the english word "square" in its meaning to "square" things such as "square feet" or "square meter" or "square kilometer" or - if the unit is now known then "square unit" for whatever the unit may be. I assume that most of my users will not cofuse this as the other meaning of the term "square" is rather fringe, meaning not common in the LiDAR and pointcloud world.
