### ISSUE TITLE
create laz without converting las

### ISSUE THREAD

**Issue by KirbX** [LAStools/LAStools#86]
Hi!
Is it possible to create a LAZ file without creating a LAS file and converting it?
It is said in the README that it is possible but I didn't find any clue how?

Should I put the flag `is_compressed` to true in the header and rename the file .laz?

Thanks a lot!
Best regards!

R.S

**Comment by rapidlasso** [comment]
There are a number of examples in this folder on how to use the LASlib library to write LAZ directly:

https://github.com/LAStools/LAStools/tree/master/LASlib/example

If you rather use the DLL then an example is here:

https://github.com/LAStools/LAStools/tree/master/LASzip/example
