### ISSUE TITLE
-soname should not be used for OS X build

### ISSUE THREAD

**Issue by elfprince13** [LAStools/LAStools#9]
The readme claims that the Makefiles should work for Mac builds; however, the -soname flag is incorrect for creating dynamic libraries on OS X.

**Comment by rapidlasso** [comment]
Currently no dynamic libraries for LASlib are compiled on either platform. What is supported via the Makefile is the compilation of a static library and the executables for the open source tools and that seems to work fine on Linux and MacOS systems.
