### ISSUE TITLE
delete lasreader  is really need?

### ISSUE THREAD

**Issue by radi2015** [LAStools/LAStools#99]
I use lastools in java with jni to read las files,
i will read many .las files in one times,
it is exception when read some .las file ，but when i remove delete the exception is disappear

is is an intelligence pointer? lasreader->close(); it have been closed,why alse need delete

**Comment by rapidlasso** [comment]
Not sure what it means to "use lastools in java with jni" but my C++ code uses "delete lasreader" in several places. Not sure if there is a bug that only surfaces "in java with jni".
